image: ruby:2.5

build:
  stage: build
  script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  artifacts:
    paths:
    - build

test:
  stage: test
  script:
  - cd tests
  - PATH=../build/tools/hscript-validate:$PATH rspec spec/validator.rb

